import React, { useEffect, useState } from 'react';
import { ComposableMap, Geographies, Geography, Marker } from 'react-simple-maps';

// TopoJSON for Pakistan Map (approximate borders for visualization)
const geoUrl = "https://raw.githubusercontent.com/deldersveld/topojson/master/countries/pakistan/pakistan-provinces.json";

const TrackMap = () => {
    const [markers, setMarkers] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        // Fetch static data generated by backend automation
        fetch('/data/members.json')
            .then(res => res.json())
            .then(data => {
                setMarkers(data);
                setLoading(false);
            })
            .catch(err => {
                console.error("Failed to load map data:", err);
                setLoading(false);
            });
    }, []);

    if (loading) {
        return <div className="text-brand-500 font-sans animate-pulse">Loading Community Footprint...</div>;
    }

    return (
        <div className="w-full h-full max-h-[600px] relative">
            <ComposableMap
                projection="geoMercator"
                projectionConfig={{
                    scale: 2500, // Zoomed in on Pakistan
                    center: [70, 30] // Longitude, Latitude for Pakistan center
                }}
            >
                <Geographies geography={geoUrl}>
                    {({ geographies }) =>
                        geographies.map((geo) => (
                            <Geography
                                key={geo.rsmKey}
                                geography={geo}
                                fill="#0a0a0a" // dark-900 base color
                                stroke="#10b981" // brand emerald borders
                                strokeWidth={0.5}
                                style={{
                                    default: { outline: "none" },
                                    hover: { fill: "#171717", outline: "none", transition: "all 0.3s" },
                                    pressed: { outline: "none" }
                                }}
                            />
                        ))
                    }
                </Geographies>

                {markers.map(({ id, name, city, coordinates, role }) => (
                    <Marker key={id} coordinates={coordinates}>
                        <g className="group cursor-pointer">
                            <circle r={4} fill="#10b981" className="animate-ping shadow-[0_0_10px_#10b981]" />
                            <circle r={12} fill="transparent" /> {/* Larger hit area for hover */}
                            <text
                                textAnchor="middle"
                                y={-10}
                                className="opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none"
                                style={{ fontFamily: "Inter", fontSize: "10px", fill: "white", textShadow: "0px 0px 5px black" }}
                            >
                                {name} ({city})
                            </text>
                        </g>
                    </Marker>
                ))}
            </ComposableMap>

            <div className="absolute bottom-4 left-4 border border-brand-500/30 bg-[#050505]/80 p-3 rounded-lg backdrop-blur">
                <p className="font-sans text-xs text-slate-400">Total Members Online: <span className="text-brand-500 font-bold">{markers.length}</span></p>
                <p className="font-sans text-xs text-slate-500 mt-1">Status: SECURE</p>
            </div>
        </div>
    );
};

export default TrackMap;
